// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
   apiKey: "AIzaSyDmUyYFofbgKZ9gugzFyaJaAiAyPERw2R4",
  authDomain: "quizapp-4d95c.firebaseapp.com",
  projectId: "quizapp-4d95c",
  storageBucket: "quizapp-4d95c.appspot.com",
  messagingSenderId: "694578849644",
  appId: "1:694578849644:web:16eda62392d32ce78ef549",
  measurementId: "G-C64CKXK23N"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmUyYFofbgKZ9gugzFyaJaAiAyPERw2R4',
    appId: '1:694578849644:web:16eda62392d32ce78ef549',
    messagingSenderId: '694578849644',
    projectId: 'quizapp-4d95c',
    storageBucket: 'quizapp-4d95c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmUyYFofbgKZ9gugzFyaJaAiAyPERw2R4',
    appId: '1:694578849644:web:16eda62392d32ce78ef549',
    messagingSenderId: '694578849644',
    projectId: 'quizapp-4d95c',
    storageBucket: 'quizapp-4d95c.appspot.com',
    iosClientId: '694578849644-e7fa74ankvfmr0opeul85fcpjnhhlj9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmUyYFofbgKZ9gugzFyaJaAiAyPERw2R4',
    appId: '1:694578849644:web:16eda62392d32ce78ef549',
    messagingSenderId: '694578849644',
    projectId: 'quizapp-4d95c',
    storageBucket: 'quizapp-4d95c.appspot.com',
    iosClientId: '694578849644-tsrsk8gvjgf55jl6ki64ab8s9s3d7tg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
